export const products = [
    { 
        id: 1, 
        name: 'Wireless Mouse', 
        category: 'Electronics', 
        price: 25.99, 
        stockQuantity: 120, 
        supplier: 'TechCo', 
        rating: 4.5, 
        reviews: 150, 
        salesLastMonth: 300, 
        releaseDate: '2022-01-15', 
        discount: 10, 
        shippingWeight: 0.2, 
        color: 'Black',
        location: 'Warehouse A'
    },
    { 
        id: 2, 
        name: 'Gaming Laptop', 
        category: 'Electronics', 
        price: 1299.99, 
        stockQuantity: 50, 
        supplier: 'GamerGear', 
        rating: 4.8, 
        reviews: 500, 
        salesLastMonth: 75, 
        releaseDate: '2021-09-10', 
        discount: 5, 
        shippingWeight: 2.5, 
        color: 'Red', 
        location: 'Warehouse B'
    },
    { 
        id: 3, 
        name: 'Bluetooth Speaker', 
        category: 'Audio', 
        price: 79.99, 
        stockQuantity: 200, 
        supplier: 'SoundMaster', 
        rating: 4.2, 
        reviews: 300, 
        salesLastMonth: 150, 
        releaseDate: '2022-04-20', 
        discount: 15, 
        shippingWeight: 1.0, 
        color: 'Blue', 
        location: 'Warehouse A'
    },
    { 
        id: 4, 
        name: '4K Monitor', 
        category: 'Electronics', 
        price: 499.99, 
        stockQuantity: 75, 
        supplier: 'VisionTech', 
        rating: 4.6, 
        reviews: 220, 
        salesLastMonth: 45, 
        releaseDate: '2022-07-05', 
        discount: 12, 
        shippingWeight: 6.0, 
        color: 'Black', 
        location: 'Warehouse C'
    },
    { 
        id: 5, 
        name: 'Smartwatch', 
        category: 'Wearables', 
        price: 199.99, 
        stockQuantity: 150, 
        supplier: 'FitTrack', 
        rating: 4.7, 
        reviews: 400, 
        salesLastMonth: 220, 
        releaseDate: '2021-11-22', 
        discount: 8, 
        shippingWeight: 0.3, 
        color: 'Silver', 
        location: 'Warehouse B'
    },
    { 
        id: 6, 
        name: 'Electric Kettle', 
        category: 'Home Appliances', 
        price: 35.99, 
        stockQuantity: 300, 
        supplier: 'HomeTech', 
        rating: 4.0, 
        reviews: 180, 
        salesLastMonth: 250, 
        releaseDate: '2022-03-14', 
        discount: 20, 
        shippingWeight: 1.2, 
        color: 'White', 
        location: 'Warehouse A'
    },
    { 
        id: 7, 
        name: 'Noise Cancelling Headphones', 
        category: 'Audio', 
        price: 199.99, 
        stockQuantity: 80, 
        supplier: 'SoundMaster', 
        rating: 4.9, 
        reviews: 600, 
        salesLastMonth: 100, 
        releaseDate: '2021-12-01', 
        discount: 18, 
        shippingWeight: 0.5, 
        color: 'Black', 
        location: 'Warehouse C'
    },
    { 
        id: 8, 
        name: 'Air Fryer', 
        category: 'Home Appliances', 
        price: 99.99, 
        stockQuantity: 180, 
        supplier: 'KitchenPro', 
        rating: 4.3, 
        reviews: 220, 
        salesLastMonth: 180, 
        releaseDate: '2022-05-30', 
        discount: 10, 
        shippingWeight: 3.0, 
        color: 'Red', 
        location: 'Warehouse B'
    },
    { 
        id: 9, 
        name: 'Tablet', 
        category: 'Electronics', 
        price: 249.99, 
        stockQuantity: 130, 
        supplier: 'TechCo', 
        rating: 4.4, 
        reviews: 350, 
        salesLastMonth: 110, 
        releaseDate: '2021-10-15', 
        discount: 15, 
        shippingWeight: 0.8, 
        color: 'Gray', 
        location: 'Warehouse A'
    },
    { 
        id: 10, 
        name: 'Smartphone', 
        category: 'Electronics', 
        price: 799.99, 
        stockQuantity: 200, 
        supplier: 'MobileTech', 
        rating: 4.7, 
        reviews: 600, 
        salesLastMonth: 500, 
        releaseDate: '2022-02-01', 
        discount: 10, 
        shippingWeight: 0.4, 
        color: 'Blue', 
        location: 'Warehouse C'
    }
];